# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado', models.CharField(max_length=100)),
                ('resolucion', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('date_inicio', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experiencia Academica',
                'verbose_name_plural': 'Experiencias Academicas',
            },
        ),
    ]
