# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0002_auto_20160616_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienciaacademica',
            name='date_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experienciaacademica',
            name='date_inicio',
            field=models.DateField(),
        ),
    ]
